### ISSUE TITLE
Incremental Project Builder + Close Editor on deleting file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#100]
```
What steps will reproduce the problem?
1. Open XMind-file in your workspace
2. Edit
3. Save

What is the expected output? What do you see instead?
Project builder has to be triggered with the IFile as resource-delta


What version of the product are you using? On what operating system?
3.0.3


```

Original issue reported on code.google.com by `tomseide...@googlemail.com` on 5 Aug 2009 at 8:56

Attachments:
- [MindMapEditor.java](https://storage.googleapis.com/google-code-attachments/xmind3/issue-100/comment-0/MindMapEditor.java)

**Comment by frankshaka** [comment]
Closing this issue as it is too old.
