### ISSUE TITLE
Unncessary / Sloppy node knots rendering in PDF

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#113]
```
What steps will reproduce the problem?
1. Create a mindmap with Child and Sub-child entries; and add labels
2. Export as PDF
3. Open PDF and witness the sloppy render

What is the expected output? What do you see instead?
I guess for once that the - signs shouldn't be displayed during export. But
if you think they should still remain (I don't see the use, it add
confusion to the mindmap), at least they should be drawn correctly.

What version of the product are you using? On what operating system?
Xmind 3 on Mac OS X 10.6 Leopard

Please provide any additional information below.

```

Original issue reported on code.google.com by `gilloust...@gmail.com` on 24 Sep 2009 at 2:38

Attachments:
- [dislocated.png](https://storage.googleapis.com/google-code-attachments/xmind3/issue-113/comment-0/dislocated.png)
- [inner circle uncentered.png](https://storage.googleapis.com/google-code-attachments/xmind3/issue-113/comment-0/inner circle uncentered.png)
- [label not filled on the left.png](https://storage.googleapis.com/google-code-attachments/xmind3/issue-113/comment-0/label not filled on the left.png)

**Comment by frankshaka** [comment]
Closing this issue as it is too old.
