### ISSUE TITLE
Summary topics child branches overlap with each other

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#140]
```
What steps will reproduce the problem?
1. Create 2 summaries placed near each other
2. Create child branches from these summaries
3. "Allow Overlaps" option is turned off

What is the expected output?
Child branches don't overlap with each other.

What do you see instead?
Child branches overlap with each other.

What version of the product are you using? On what operating system?
Xmind 3.1.1, Ubuntu 9.04

See attached screenshoot.


```

Original issue reported on code.google.com by `siarhei....@gmail.com` on 16 Dec 2009 at 12:04

Attachments:
- [overlap.png](https://storage.googleapis.com/google-code-attachments/xmind3/issue-140/comment-0/overlap.png)

**Comment by frankshaka** [comment]
Closing this issue as it is too old.

**Comment by karimalashry** [comment]
I found a trick, can help fixing this bug

-You can make a callout to any topic

-Move callout in the way allow you avoiding overlapping manually

-Finally u can change color of callout to be as the background, make it borderless & delete the text so it becomes invisible

I hope this will be helpful for you

**Comment by karimalashry** [comment]
This is a better trick more helpful
https://youtu.be/dVlclYB3TnA
