### ISSUE TITLE
Incomplete a topic title

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#184]
```
What steps will reproduce the problem?
1. Topic title is sometimes incomplete. Look at the attached file
2.
3.

What is the expected output? What do you see instead?
Complete title? ;?)

What version of the product are you using? On what operating system?
Version: 3.1.1

Please provide any additional information below.


```

Original issue reported on code.google.com by `nesn...@gmail.com` on 22 Jun 2010 at 10:28

Attachments:
- [xmindIncompleteTitle.png](https://storage.googleapis.com/google-code-attachments/xmind3/issue-184/comment-0/xmindIncompleteTitle.png)

**Comment by frankshaka** [comment]
Closing this issue as it is too old.
