### ISSUE TITLE
XMind doesn't run

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#19]
```
What steps will reproduce the problem?
1. Just installed XMind.
2. Just run XMind.
3. XMind only shows the window below.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
3.0.1

Please provide any additional information below.


```

Original issue reported on code.google.com by `tomophy` on 15 Jan 2009 at 1:24

Attachments:
- [WS000000.jpg](https://storage.googleapis.com/google-code-attachments/xmind3/issue-19/comment-0/WS000000.jpg)

**Comment by frankshaka** [comment]
Closing this issue as it's too old.

**Comment by michael-ts** [comment]
@frankshaka  what a joke!
