### ISSUE TITLE
how can i create custom marker icons?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#217]
```
can i create custom marker icons by myself?
any tool?
what's the metadata xml structure?
what's the icons spec?

thanks
```

Original issue reported on code.google.com by `missed...@gmail.com` on 14 Jan 2011 at 5:40

**Comment by frankshaka** [comment]
Please see https://github.com/xmindltd/xmind/wiki/XMindFileFormat#markersheetxml for documentation of marker sheet elements.
