### ISSUE TITLE
Overlapping branches when using summary nodes.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#228]
```
What steps will reproduce the problem?

1. Create summary node with enough descendants
2. Create sibling node with enough descendants

What is the expected output? What do you see instead?

I expect that the summary node descendants are included in determining the 
space for layout.
I see that summary node descendants overlap sibling node descendants.

What version of the product are you using? On what operating system?

XMind 3.2.1, Mac OS X

Please provide any additional information below.

An annotated screenshot is attached.
```

Original issue reported on code.google.com by `ghackenb...@gmail.com` on 22 Jul 2011 at 11:52

Attachments:
- [bug.png](https://storage.googleapis.com/google-code-attachments/xmind3/issue-228/comment-0/bug.png)

**Comment by frankshaka** [comment]
Closing this issue as it is too old.

**Comment by karimalashry** [comment]
Any fix?!

**Comment by karimalashry** [comment]
I found a trick, can help fixing this bug

-You can make a callout to any topic

-Move callout in the way allow you avoiding overlapping manually

-Finally u can change color of callout to be as the background, make it borderless & delete the text so it becomes invisible

I hope this will be helpful for you

**Comment by karimalashry** [comment]
This is a better trick more helpful
https://youtu.be/dVlclYB3TnA
