### ISSUE TITLE
org.eclipse.ui.internal.ShowViewAction deleted in eclipse 4.5 release

### ISSUE THREAD

**Issue by nacerix** [xmindltd/xmind#259]
According to bug 440980, ShowViewAction.java file has been deleted. For this reason, it is not possible to build xmind using recent eclipse releases.
Is there a work around?

**Comment by frankshaka** [comment]
Failure to build on Eclipse 4.x is caused by some hard dependencies upon internal Eclipse 3.x classes. We're working on this issue and XMind 3.6 will be based on Eclipse 4.5. XMind <=3.5.3 can only be built on Eclipse <=3.8.2.
