### ISSUE TITLE
Can not compile with Eclipse 4

### ISSUE THREAD

**Issue by nielinjie** [xmindltd/xmind#260]
Some classes are removed from Eclipse 4 - 

org.eclipse.ui.internal.EditorManager
org.eclipse.ui.internal.ShowViewAction

**Comment by frankshaka** [comment]
XMind v3.5.x can only be compiled against Eclipse 3.x (up to 3.8.2). New v3.6.0 coming soon will be compatible with e4. Stay tuned!

**Comment by frankshaka** [comment]
See this new guide https://github.com/xmindltd/xmind/wiki/How-To-Build-XMind-From-Source
