### ISSUE TITLE
Manual proxy configuration ignored or not working when connecting to Evernote

### ISSUE THREAD

**Issue by ilvetz** [xmindltd/xmind#262]
Using Xmind 7 Free (v3.6.1) on Windows 7, planning upgrade to Pro.

I can't connect to Evernote because of corporate proxy.

Configuring SOCKS proxy without authentication (SSH tunnel), both using internal or external browser, does not work.

I always transit through the native one obtaining Websense block page. Surfing the Internet with Chrome via SSH tunnel does work.

Thank you so much for any update on this.

**Comment by frankshaka** [comment]
'Save to Evernote' feature currently only use internal browser, and according to this Eclipse' issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=82295 the internal browser seems not to support manual proxy settings on Windows, which IMHO should instead be configured using system's settings. If that does not work either, i'm sorry that there may not be much we can help for this issue.
