### ISSUE TITLE
Command to run Xmind with External Debugger

### ISSUE THREAD

**Issue by CuchulainX** [xmindltd/xmind#264]
I'd like to run XMind via the Enterprise Architect Java Profiler and am not having much success

How can I launch XMind without Eclipse as EA can't Profile while Eclipse is debugging

I discovered this online for Linux - I guess I'm looking for the Windows equivalent

Thanks
/Cuchulain

Start VM: /usr/bin/java
-jar /usr/lib/xmind//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /usr/lib/xmind/XMind
-name XMind
--launcher.library /usr/lib/xmind//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417/eclipse_1612.so
-startup /usr/lib/xmind//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.overrideVmargs
-exitdata 7a8014
-configuration @user.home/.xmind/configuration-cathy_linux_64
-data @user.home/.xmind/workspace-cathy
-debug
-vm /usr/bin/java
-vmargs
-jar /usr/lib/xmind//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
Configuration location:
file:/home/tibo/.xmind/configuration-cathy_linux_64/
Configuration file:
file:/home/tibo/.xmind/configuration-cathy_linux_64/config.ini loaded
Install location:
file:/usr/lib/xmind/
Configuration file:
file:/usr/lib/xmind/configuration/config.ini loaded
Loading timestamp file from:
file:/home/tibo/.xmind/configuration-cathy_linux_64/ .baseConfigIniTimestamp
No timestamp file found
Timestamps found:
config.ini in the base: 1447071333000
remembered -1
Shared configur

**Comment by frankshaka** [comment]
The way to launch XMind on Windows using pure Java is basically the same with what you posted. You just need to replace some variables, e.g. `linux` -> `win32`, `gtk` -> `win32`, `eclipse_**.so` -> `eclipse_**.dll`. Hope you good luck!
