### ISSUE TITLE
Undo not available in Notes on Mac

### ISSUE THREAD

**Issue by seanwood** [xmindltd/xmind#269]
XMind version 7.5 Update 1 (R3.6.51.201607142338)
Mac OS X 10.12 (16A323)

Steps to reproduce:
1) Select a node and open the Notes view: Window Menu -> Notes
2) Enter or modify text
3) Undo is not enabled in the Edit menu, and the keyboard shortcut (Command-Z) doesn't work

Workaround:
1) Change the focus away from the Notes view
2) Undo becomes available: Edit Menu -> Undo Modify Notes

**Comment by frankshaka** [comment]
Fixed in v3.7.0
