### ISSUE TITLE
xmind 8 cannot change language

### ISSUE THREAD

**Issue by anvish** [xmindltd/xmind#275]
![xmind-error](https://cloud.githubusercontent.com/assets/1114090/20029931/39f9716e-a36b-11e6-8f89-ea278f2f4924.png)
Selecting "Language" item leads to error. After selecting other item ("Advanced"), "Language" can be selected, but shows empty page.
![xmind-error-2](https://cloud.githubusercontent.com/assets/1114090/20029943/9407dec0-a36b-11e6-9151-e26de18f383e.png)

**Comment by kyxap1** [comment]
I can confirm this problem under OS X, Linux and Windows

###Solutions
**OS X** Run as: /Applications/XMind.app/Contents/MacOS/XMind -AppleLanguages '(en-US)'
**Linux** Run xmind with environment variable LANG=C

**Comment by Shawn1** [comment]
Hello,

This problem has been fixed for almost half a year. Please try new version of XMind 8. Thank you.
