### ISSUE TITLE
Where to download xmind 8(v3.7.0)  Portable Package (Win+Mac+Linux in a zip)?

### ISSUE THREAD

**Issue by aihua** [xmindltd/xmind#278]
Where to download xmind 8(v3.7.0)  Portable Package (Win+Mac+Linux in a zip)?

Portable Package(Win+Mac+Linux in a zip) as http://www.xmind.net/xmind/downloads/xmind-7.5-portable.zip for XMind 7.5 (v3.6.51) or http://www.xmind.net/xmind/downloads/xmind-portable-3.5.3.201506180105.zip for XMind 6 (v3.5.3).

**Comment by Frodox** [comment]
Looks line nowhere. It is too heavy (300MB) now, so, I think, they decided to split it.

**Comment by malliwi88** [comment]
http://dl2.xmind.net/xmind-downloads/xmind-7.5-update1-portable.zip

**Comment by frankshaka** [comment]
The official site does not provide downloads for such 3-in-1 package for XMind 8. If you use multiple Windows machines, there's a [portable version for Windows](https://www.xmind.net/xmind/downloads/xmind-8-update5-windows.zip).
