### ISSUE TITLE
Changes on installation script & process

### ISSUE THREAD

**Issue by WolfangAukang** [xmindltd/xmind#283]
Hello guys,

Today I was testing your application on my PC with Fedora, and there were some issues I had to address:

- The setup.sh only installs dependencies for Debian and Ubunutu based distros, because of apt-get. On Fedora (hopeful it does work on RHEL and CentOS, who have YUM), DNF must install java-1.8.0-openjdk.x86_64, lame, glibc and webkitgtk to work.
- Later, the latter script does not move the file with the program content, only the Truetype fonts.
- Finally, there is no .desktop file

Would it be possible to fix it?

Thanks for the support.

**Comment by Shawn1** [comment]
Hello WolfangAukang,

1. You may custom your local "setup.sh" file by yourself, according to your requirement and your platform.
2. For ".desktop" file, you could create hyperlink from the launcher. If it can't work, please modify "XMind.ini" -> -startup & --launcher.library value from relative to absolute path.
Thanks.

**Comment by WolfangAukang** [comment]
Thanks for the response, Shawn:

1.  I understand. The point is at least to indicate somewhere for users to install those dependencies. I mean, there are a lot of users outside of Debian/Ubuntu that use this software, so this would be helpful for them.
2. Yeah, I did that, and worked.

Closing this issue.
