### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by SerryYang** [xmindltd/xmind#285]
This Error  

Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWTError cannot be found by org.eclipse.ui.workbench_3.108.0.v20160602-1232

Environment :

-  (code)Release 3.7.0.201611010032
- xmind-8
- jdk_1.8
- Eclipse SDK v4.6 64bit

How to solve it?

Thank you for much!

**Comment by Frodox** [comment]
You would have more chances to get the answer, if you share
* version of xmind
* which distro
* java version?

**Comment by SerryYang** [comment]
- Release 3.7.0.201611010032

- xmind-8-windows.zip

- java :jdk_1.8

(Eclipse SDK v4.6  64bit )

Thank you for much!!!
