### ISSUE TITLE
Can I use api out of eclipse env?

### ISSUE THREAD

**Issue by nielinjie** [xmindltd/xmind#287]
Is this possible? I just want to parse a xmind file and get content to do some convert/export.

**Comment by grldsndrs** [comment]
The contents of the xmind file can be seen by changing the extension to .Zip from .xmind

**Comment by grldsndrs** [comment]
Parsing XMind file

XMind files are generated in XMind Workbook (.xmind) format, an open format that is based on the principles of OpenDocument. It consists of a ZIP compressed archive containing separate XML documents for content and styles, a .jpg image file for thumbnails, and directories for related attachments.

XMind/XMind Pro 3 and later should support the older version ".xmap" file format (XMind 2007/2008), but are limited to reading it.

**Comment by sappling** [comment]
@nielinjie - yes, you can parse/generate xmind files outside of the full application.  See the wiki for some examples of using the API.  I'm not an expert on this, but I have made some similar import/export tools just using the org.xmind.core_<version>.jar file from either an xmind source build or from the downloadable distribution.

**Comment by ZhuShouCheng** [comment]
@sappling Can you give me your tools ? thanks

**Comment by sappling** [comment]
The primary tool I'm working on is not ready yet, but I did check in some very simple samples at [sappling/xmindapi](https://github.com/sappling/xmindapi).  I'll add some more there as I continue to explore using XMind programatically.  Hopefully this will be helpful for others.  It has taken me a while to struggle with getting markers and styles to work as I expected.

**Comment by frankshaka** [comment]
You can export the org.xmind.core bundle as a JAR file and include it in any Java project. This bundle depends solely on the standard JRE and can be included using classic `-classpath` option.
