### ISSUE TITLE
Update GitHub releases

### ISSUE THREAD

**Issue by baimafeima** [xmindltd/xmind#291]
Is there a specific reason (e.g. licenses) why Xmind 8 is not released here on GitHub? I am a bit confused about your versioning. What is, for example, the difference between 3.7.0 and 7.5? Why not have a clearer versioning policy?

**Comment by udp** [comment]
It seems to be some kind of confusion exercise to try to get you to end up on the download page for the "pro" version.  Guess I'm going to have to build it myself...

**Comment by frankshaka** [comment]
The version 3.7.0 is for XMind 8 builds. The phrase "XMind 8" is the product name and it's for marketing purpose only.
