### ISSUE TITLE
I am very sorry that I delete the Wiki page of UsingXmindAPI....  How can I recover it? 

### ISSUE THREAD

**Issue by ZhuShouCheng** [xmindltd/xmind#297]

**Comment by Frodox** [comment]
I think, maybe via clonning wiki `https://github.com/xmindltd/xmind.wiki.git` and reverting last commit

**Comment by sappling** [comment]
I did not have rights to push the reverted wiki back, but I did recreate the page.

**Comment by Frodox** [comment]
yes, you can recreate it manually via web :)

**Comment by frankshaka** [comment]
I'm closing this as the page is back :)
