### ISSUE TITLE
API for Reading/Saving Files is Deprecated

### ISSUE THREAD

**Issue by vostok4** [xmindltd/xmind#299]
I'm trying to do some simple stuff, open an Xmind workbook using the API, edit a title text, then save it.

There's no way I can actually save my changes, `workbook.save("filename.xmind")` won't write any data. Also, loadFromPath/loadFromFile are deprecated, how should we be interacting with the API?

Also, would it ever be possible to generate SVG files from the API? It looks like it is tightly coupled with the actual window rendering?

**Comment by frankshaka** [comment]
Please see the [ISerializer](https://github.com/xmindltd/xmind/blob/master/bundles/org.xmind.core/src/org/xmind/core/ISerializer.java) class and the [IDeserializer](https://github.com/xmindltd/xmind/blob/master/bundles/org.xmind.core/src/org/xmind/core/IDeserializer.java) class for new methods of saving/loading XMind workbook files.

**Comment by p1094358629** [comment]
how about create a example .i am confused about this also

**Comment by Aaron-maker** [comment]
大佬 有示例嘛

**Comment by Aaron-maker** [comment]
> 我正在尝试做一些简单的事情，使用API​​打开Xmind工作簿，编辑标题文本，然后保存它。
> 
> 我实际上无法保存更改，`workbook.save("filename.xmind")`不会写入任何数据。另外，不建议使用loadFromPath / loadFromFile，我们应该如何与API交互？
> 
> 另外，是否有可能通过API生成SVG文件？看起来它与实际的窗口渲染紧密结合了吗？


示例怎么写
How to write an example  thank!
