### ISSUE TITLE
performance issue on Macbook pro with high sierra

### ISSUE THREAD

**Issue by Deguang** [xmindltd/xmind#301]
After upgrade OS to high sierra , xmind 8(3.7.5) be worked slowly when typing or dragging.
Please improve performance on latest macOs.

If you need more details, please tell me how to collect data.

**Comment by Shawn1** [comment]
Hello Deguang,

We have just fixed it not long ago, and will publish it in our new update version of XMind 8 soon.
Thankyou~

**Comment by Deguang** [comment]
@Shawn1 It's a good news～ I really appreciate it.
