### ISSUE TITLE
Can't visit website xmind.net

### ISSUE THREAD

**Issue by simadad** [xmindltd/xmind#334]
![image](https://user-images.githubusercontent.com/21257526/65854329-f104de00-e38e-11e9-87eb-f6895e95b701.png)

endless loop to redirect a css file

**Comment by ServerDestroyer** [comment]
I have not been able to access their website for years now... They (xmind company or whoever) left there Facebook and 'email list' ads on auto but the site has been dead for a long time. Their last update was {XMind 8 (v3.7.2) / 4 May 2017} 2 years ago.

**Comment by Dirk-** [comment]
@ServerDestroyer @simadad  Their website is working for me. I visit it from time to time, no problem. The last update for XMind 8 available is Update 8 from Juli 2018. They are working on XMind Zen now.

**Comment by ServerDestroyer** [comment]
So I am in the USA and I cannot access 'https://www.xmind.net/' (I used tried PCs and VPN locations) but when I use Tor I can. I have never seen anything like this. Could this have something to do with the problem? Can anyone else in the USA access? (try VPN to test if needed)

**Comment by tgreve15** [comment]
Works fine for me from Australia and using a VPN connection to California
both from my phone

**Comment by simadad** [comment]
i have used a chrome plugin to redirect Google API last time,  and now i can visit website after i disable it

**Comment by ServerDestroyer** [comment]
So, I found that my host file was point at 0.0.0.0 for xmind.net. I also found this on my other PCs. I have no idea what would have done this but it is fixed. Well, anyways this is closed out now.
