### ISSUE TITLE
FreeMind import looses all multiline topics

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#70]
```
What steps will reproduce the problem?
1. Create de FreeMind mind map with multiline topics (not notes, the
content is in the topic)
2. Import the FreeMind map in XMind

What is the expected output? What do you see instead?

Every  multiline topic is replaced by the single word "Subtopic", the
original text seems to be lost.

What version of the product are you using? On what operating system?

XMind 3.0.3, xmind-linux-3.0.3.200904291819_i386.deb on Ubuntu 9.04

Please provide any additional information below.

I attached an sample .mm file and the imported .xmind version.

```

Original issue reported on code.google.com by `Farzad.F...@gmail.com` on 30 Apr 2009 at 5:10

Attachments:
- [Xmind-Freemind-import-bug.mm](https://storage.googleapis.com/google-code-attachments/xmind3/issue-70/comment-0/Xmind-Freemind-import-bug.mm)
- [Xmind looses every multiline Topic.xmind](https://storage.googleapis.com/google-code-attachments/xmind3/issue-70/comment-0/Xmind looses every multiline Topic.xmind)

**Comment by frankshaka** [comment]
Closing this issue as it is too old.
