### ISSUE TITLE
Box border clipping issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#85]
```
What steps will reproduce the problem?

1. Type text in most boxes (topic boxes and label boxes tested)
2. a lot of the time the text is cut-off mid-letter e.g. you can't read the
text fully because the border of the box it is in cuts it off.
3. Especially bad when text is 'lengthy'.


What is the expected output? What do you see instead?

Expected output - text that is not cut-short.
See instead - text that is cut short by the border of the box it is in.


What version of the product are you using? On what operating system?

Xmind 3.0.3
Linux Ubuntu 9.04


Please provide any additional information below.

Thank you for taking the time to read this. And thanks for an otherwise
great program :-)
```

Original issue reported on code.google.com by `mhcabi@gmail.com` on 18 Jun 2009 at 8:11

**Comment by maxpietsch** [comment]
The same here. The clipping is worst for default font size 14 (font Noteworthy or Verdana). All other tested font sizes do not clip the last letter but the box margin is still not symmetric. See for instance: http://www.xmind.net/m/g8rK/

Ubuntu
 $ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1), 
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

**Comment by frankshaka** [comment]
Closing this issue as it is too old.
